/**
 * {{pluginId}} — browser half of {{title}} (FULLSCREEN layout).
 * Auto-generated by `npx @flowot/nx-pn init <name> --layout fullscreen`.
 *
 * Self-rendered topbar + nested routes via react-router-dom:
 *   /home         overview (landing)
 *   /diagnostics  hostCall tests + result panel
 *   /settings     pluginStorage demo (read/write settings | cache | state)
 *   /about        placeholder
 *
 * The host half exposes the same tool endpoints as the sidebar scaffold
 * — only the browser layout differs.
 */

import { useState } from 'react'
import { Link, Route, Routes, useLocation } from 'react-router-dom'

interface BrowserCtx {
  logger: { info(m: string): void }
  pages: {
    register(entry: {
      pluginId: string
      path: string
      title: string
      order?: number
      /** 'shell' (sidebar, default) | 'fullscreen' (hides sidebar, own topbar) */
      layout?: 'shell' | 'fullscreen'
      Component?: unknown
    }): unknown
  }
  hostCall: <T = unknown>(event: string, payload?: unknown) => Promise<T>
}

const browserHalf = function browserHalf(ctx: BrowserCtx, config?: { name?: string }): void {
  const id = config?.name ?? '{{pluginId}}'
  ctx.logger.info(`[${id}] browser half active (fullscreen)`)

  async function run<T>(event: string, payload?: unknown): Promise<{ ok: boolean; data?: T; error?: string }> {
    try {
      const r = (await ctx.hostCall(event, payload)) as { ok?: boolean; data?: T; error?: string } | T
      if (r && typeof r === 'object' && 'ok' in r) return r as { ok: boolean; data?: T; error?: string }
      return { ok: true, data: r as T }
    } catch (e) {
      return { ok: false, error: e instanceof Error ? e.message : String(e) }
    }
  }

  function Home() {
    return (
      <div className="page">
        <h1>{{title}}</h1>
        <div className="muted">Plugin <code>{id}</code> — fullscreen layout.</div>
        <ul>
          <li><Link to="diagnostics">Diagnostics</Link> — call host tool endpoints</li>
          <li><Link to="settings">Settings</Link> — read/write pluginStorage</li>
          <li><Link to="about">About</Link></li>
        </ul>
      </div>
    )
  }

  function Diagnostics() {
    const [busy, setBusy] = useState<string | null>(null)
    const [result, setResult] = useState<unknown>(null)
    async function go(name: string, event: string, payload?: unknown) {
      setBusy(name); setResult(null)
      const r = await run(event, payload)
      setResult(r)
      setBusy(null)
    }
    const btn = (label: string, name: string, event: string, payload?: unknown) => (
      <button disabled={busy !== null} onClick={() => go(name, event, payload)}>{busy === name ? '…' : label}</button>
    )
    return (
      <div className="page">
        <h2>Diagnostics</h2>
        <div className="form-actions">
          {btn('Health check', 'h', `${id}/health-check`)}
          {btn('Read boot count', 'b', `${id}/boot-count`)}
          {btn('Read settings:lastTs', 'r', `${id}/storage-read`, { table: 'settings', key: 'lastTs' })}
          {btn('Write settings:lastTs', 'w', `${id}/storage-write`, { table: 'settings', key: 'lastTs', value: Date.now() })}
        </div>
        <pre>{result === null ? '(no result)' : JSON.stringify(result, null, 2)}</pre>
      </div>
    )
  }

  function Settings() {
    type Table = 'settings' | 'cache' | 'state'
    const [table, setTable] = useState<Table>('settings')
    const [key, setKey] = useState('demoKey')
    const [value, setValue] = useState('')
    const [read, setRead] = useState<unknown>(undefined)
    const [err, setErr] = useState<string | null>(null)

    async function doRead() {
      setErr(null)
      const r = await run(`${id}/storage-read`, { table, key })
      if (r.ok) setRead(r.data)
      else setErr(r.error ?? 'unknown')
    }
    async function doWrite() {
      setErr(null)
      let parsed: unknown = value
      try { parsed = JSON.parse(value) } catch { /* keep as string */ }
      const r = await run(`${id}/storage-write`, { table, key, value: parsed })
      if (!r.ok) setErr(r.error ?? 'unknown')
      else doRead()
    }

    return (
      <div className="page">
        <h2>Settings (pluginStorage demo)</h2>
        <div className="form-actions">
          <label>table:&nbsp;
            <select value={table} onChange={(e) => setTable(e.target.value as Table)}>
              <option>settings</option><option>cache</option><option>state</option>
            </select>
          </label>
          <label>key:&nbsp;<input value={key} onChange={(e) => setKey(e.target.value)} /></label>
        </div>
        <div className="form-actions">
          <label>value:&nbsp;<input value={value} onChange={(e) => setValue(e.target.value)} placeholder="JSON or string" /></label>
          <button onClick={doWrite}>Write</button>
          <button onClick={doRead}>Read</button>
        </div>
        {err && <pre className="error">{err}</pre>}
        <pre>{read === undefined ? '(not loaded)' : JSON.stringify(read, null, 2)}</pre>
      </div>
    )
  }

  function About() {
    return (
      <div className="page">
        <h2>About</h2>
        <p>Plugin <code>{id}</code>. Edit <code>browser-fullscreen.tsx</code> to customize.</p>
      </div>
    )
  }

  function Topbar() {
    const loc = useLocation()
    return (
      <header className="topbar">
        <Link to="home"><strong>{{title}}</strong></Link>
        <nav>
          <Link to="home">Home</Link>
          <Link to="diagnostics">Diagnostics</Link>
          <Link to="settings">Settings</Link>
          <Link to="about">About</Link>
        </nav>
        <span className="muted">{loc.pathname}</span>
      </header>
    )
  }

  function FullscreenRoot() {
    return (
      <div className="fullscreen-root">
        <Topbar />
        <main>
          <Routes>
            <Route path="home" element={<Home />} />
            <Route path="diagnostics" element={<Diagnostics />} />
            <Route path="settings" element={<Settings />} />
            <Route path="about" element={<About />} />
            <Route path="*" element={<Home />} />
          </Routes>
        </main>
      </div>
    )
  }

  ctx.pages.register({
    pluginId: id,
    path: '/' + id,
    title: '{{title}}',
    order: 200,
    layout: 'fullscreen',
    Component: FullscreenRoot,
  })
}

;(browserHalf as typeof browserHalf & { inject?: string[] }).inject = ['pages']
export default browserHalf