/**
 * {{pluginId}} — browser half of {{title}} (SIDEBAR layout).
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * Registers one page in the web shell's sidebar. Four test buttons
 * exercise the host half's tool endpoints; results render in the
 * <pre> below.
 *
 * Pass `--layout fullscreen` to get nested routes via react-router-dom
 * (see browser-fullscreen.tsx).
 */

import { useState } from 'react'

interface BrowserCtx {
  logger: { info(m: string): void }
  pages: {
    register(entry: {
      pluginId: string
      path: string
      title: string
      order?: number
      /** 'shell' (sidebar, default) | 'fullscreen' (hides sidebar, own topbar) */
      layout?: 'shell' | 'fullscreen'
      Component?: unknown
    }): unknown
  }
  hostCall: <T = unknown>(event: string, payload?: unknown) => Promise<T>
}

const browserHalf = function browserHalf(ctx: BrowserCtx, config?: { name?: string }): void {
  const id = config?.name ?? '{{pluginId}}'
  ctx.logger.info(`[${id}] browser half active (sidebar)`)

  const PageComponent = () => {
    const [busy, setBusy] = useState<string | null>(null)
    const [result, setResult] = useState<unknown>(null)
    const [error, setError] = useState<string | null>(null)

    async function run(name: string, event: string, payload?: unknown) {
      setBusy(name); setError(null); setResult(null)
      try {
        const r = await ctx.hostCall(event, payload)
        setResult(r)
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
      } finally {
        setBusy(null)
      }
    }

    const btn = (label: string, name: string, event: string, payload?: unknown) => (
      <button disabled={busy !== null} onClick={() => run(name, event, payload)}>
        {busy === name ? '…' : label}
      </button>
    )

    return (
      <div className="page">
        <h1>{{title}}</h1>
        <div className="muted">Plugin <code>{id}</code> — sidebar layout. Tests call the host half.</div>

        <section className="card">
          <h2>Tests</h2>
          <div className="form-actions">
            {btn('Health check', 'health', `${id}/health-check`)}
            {btn('Read boot count', 'boot', `${id}/boot-count`)}
            {btn('Read settings:lastTs', 'read', `${id}/storage-read`, { table: 'settings', key: 'lastTs' })}
            {btn('Write settings:lastTs', 'write', `${id}/storage-write`, { table: 'settings', key: 'lastTs', value: Date.now() })}
          </div>
        </section>

        <section className="card">
          <h2>Result</h2>
          {error && <pre className="error">{error}</pre>}
          {!error && (
            <pre>{result === null ? '(none yet — click a button)' : JSON.stringify(result, null, 2)}</pre>
          )}
        </section>
      </div>
    )
  }

  ctx.pages.register({
    pluginId: id,
    path: '/' + id,
    title: '{{title}}',
    order: 200,
    layout: 'shell',
    Component: PageComponent,
  })
}

;(browserHalf as typeof browserHalf & { inject?: string[] }).inject = ['pages']
export default browserHalf