/**
 * {{pluginId}} — browser half of {{title}}.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 */

import { useState } from 'react'

interface BrowserCtx {
  logger: { info(m: string): void }
  pages: {
    register(entry: { pluginId: string; path: string; title: string; order?: number; Component?: unknown }): unknown
  }
}

const browserHalf = function browserHalf(ctx: BrowserCtx, config?: { name?: string }): void {
  const id = config?.name ?? '{{pluginId}}'
  ctx.logger.info(`[${id}] browser half active`)

  const PageComponent = () => {
    const [count, setCount] = useState(0)
    return (
      <div className="page">
        <h1>{{title}}</h1>
        <div className="muted">Plugin <code>{id}</code> browser half.</div>
        <section className="card">
          <h2>React Validation</h2>
          <p>useState counter: <strong>{count}</strong></p>
          <div className="form-actions">
            <button onClick={() => setCount((c) => c + 1)}>Increment</button>
          </div>
        </section>
      </div>
    )
  }

  ctx.pages.register({
    pluginId: id,
    path: '/' + id,
    title: '{{title}}',
    order: 200,
    Component: PageComponent,
  })
}

;(browserHalf as typeof browserHalf & { inject?: string[] }).inject = ['pages']
export default browserHalf
