/**
 * {{pluginId}} — host-half smoke tests.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * Run from the workspace root:
 *   npm test
 *
 * node:test + tsx — no vitest, keeping workspace devDeps minimal.
 * The host half is dependency-free (self-contained interfaces), so we feed
 * it a mock ctx that captures ctx.on handlers and fakes pluginStorage:
 * no running host, no network, no cordis.
 */
import test from 'node:test'
import assert from 'node:assert/strict'

import plugin from './host.js'

type Handler = (payload?: unknown) => unknown

function makeCtx() {
  const handlers = new Map<string, Handler>()
  const store = new Map<string, unknown>()
  const table = (name: 'settings' | 'cache' | 'state') => ({
    get: (key: string): unknown => store.get(name + ':' + key),
    put: async (key: string, value: unknown): Promise<void> => {
      store.set(name + ':' + key, value)
    },
  })
  const ctx = {
    logger: { info(): void {}, warn(): void {}, error(): void {} },
    on(event: string, handler: Handler): void {
      handlers.set(event, handler)
    },
    // Activation fires one hello-call; stub it so tests never touch the network.
    auditClient: {
      get: async () => ({ status: 200, statusText: 'OK', bodyText: '' }),
    },
    pluginStorage: { ns: '{{pluginId}}', table },
  }
  return { ctx, handlers }
}

const call = (handlers: Map<string, Handler>, event: string, payload?: unknown) => {
  const h = handlers.get(event)
  if (!h) throw new Error('handler not registered: ' + event)
  return h(payload) as Promise<{ ok: boolean; data?: Record<string, unknown>; error?: string }>
}

test('activation registers the three tool endpoints', async () => {
  const { ctx, handlers } = makeCtx()
  await plugin(ctx)
  assert.ok(handlers.has('{{pluginId}}/health-check'))
  assert.ok(handlers.has('{{pluginId}}/storage-read'))
  assert.ok(handlers.has('{{pluginId}}/storage-write'))
})

test('health-check reports ns + boot count', async () => {
  const { ctx, handlers } = makeCtx()
  await plugin(ctx)
  const res = await call(handlers, '{{pluginId}}/health-check')
  assert.equal(res.ok, true)
  assert.equal((res.data as { ns: string }).ns, '{{pluginId}}')
  assert.equal((res.data as { bootCount: number }).bootCount, 1)
})

test('storage-write then storage-read roundtrips through pluginStorage', async () => {
  const { ctx, handlers } = makeCtx()
  await plugin(ctx)
  const w = await call(handlers, '{{pluginId}}/storage-write', {
    table: 'settings',
    key: 'greeting',
    value: 'hello',
  })
  assert.equal(w.ok, true)
  const r = await call(handlers, '{{pluginId}}/storage-read', {
    table: 'settings',
    key: 'greeting',
  })
  assert.equal(r.ok, true)
  assert.equal((r.data as { value: unknown }).value, 'hello')
})

test('storage endpoints reject malformed payloads', async () => {
  const { ctx, handlers } = makeCtx()
  await plugin(ctx)
  const noKey = await call(handlers, '{{pluginId}}/storage-read', {})
  assert.equal(noKey.ok, false)
  const badTable = await call(handlers, '{{pluginId}}/storage-write', {
    table: 'nope',
    key: 'k',
    value: 1,
  })
  assert.equal(badTable.ok, false)
})
