/**
 * {{pluginId}} — host half of {{title}}.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * What this scaffold does:
 *   1. Increments a durable boot counter in this plugin's own namespace
 *      storage (ctx.pluginStorage — survives stop / remove / re-install).
 *   2. Fires one hello-call at activation so /audit shows a record
 *      attributed to {{pluginId}}.
 *   3. Registers three tool endpoints the browser half invokes via
 *      ctx.hostCall('<id>/<endpoint>', payload):
 *        - {{pluginId}}/health-check   → {status, ts, ns, bootCount}
 *        - {{pluginId}}/storage-read   → {table, key} → value
 *        - {{pluginId}}/storage-write  → {table, key, value} → ok
 *
 * Add your own tool endpoints below — ctx.on('<id>/<name>', handler).
 */

interface HostCtx {
  logger: { info(m: string): void; warn(m: string): void; error(m: string): void }
  on(event: string, handler: (payload?: unknown) => unknown): unknown
  auditClient: {
    get(url: string, config?: { headers?: Record<string, string>; timeoutMs?: number }): Promise<{ status: number; statusText: string; bodyText: string }>
  }
  /** Per-plugin durable KV — three tables (settings / cache / state). */
  pluginStorage?: {
    ns: string
    table(name: 'settings' | 'cache' | 'state'): {
      get(key: string): unknown
      put(key: string, value: unknown): Promise<void>
    }
  }
}

type PluginFn = ((ctx: HostCtx, config?: { name?: string }) => void) & { inject?: string[] }

const DEFAULT_URL = 'https://httpbin.org/get'

const plugin = async function plugin(ctx: HostCtx, config?: { name?: string }): Promise<void> {
  const id = config?.name ?? '{{pluginId}}'
  ctx.logger.info(`[${id}] host half active`)

  // (1) Durable boot counter — this plugin's own namespace storage.
  let bootCount = 0
  if (ctx.pluginStorage) {
    const settings = ctx.pluginStorage.table('settings')
    const current = settings.get('bootCount')
    bootCount = (typeof current === 'number' ? current : 0) + 1
    try {
      await settings.put('bootCount', bootCount)
      ctx.logger.info(`[${id}] boot #${bootCount} recorded in ns ${ctx.pluginStorage.ns}`)
    } catch (err) {
      ctx.logger.warn(`[${id}] bootCount persist failed: ${(err as Error).message}`)
    }
  }

  // (2) Hello at activation — fire-and-forget; lands on /audit with initiator={{pluginId}}.
  void ctx.auditClient.get(DEFAULT_URL).catch(() => {})

  // (3) Tool endpoints — browser half calls these via ctx.hostCall.
  ctx.on('{{pluginId}}/health-check', () => ({
    ok: true,
    data: { status: 'ok', ts: Date.now(), ns: ctx.pluginStorage?.ns ?? null, bootCount },
  }))

  ctx.on('{{pluginId}}/storage-read', (payload) => {
    const p = (payload ?? {}) as { table?: string; key?: string }
    if (!p.table || !p.key) return { ok: false, error: 'table and key required' }
    if (!ctx.pluginStorage) return { ok: false, error: 'pluginStorage not available' }
    if (p.table !== 'settings' && p.table !== 'cache' && p.table !== 'state') {
      return { ok: false, error: 'table must be settings | cache | state' }
    }
    const value = ctx.pluginStorage.table(p.table).get(p.key)
    return { ok: true, data: { table: p.table, key: p.key, value } }
  })

  ctx.on('{{pluginId}}/storage-write', async (payload) => {
    const p = (payload ?? {}) as { table?: string; key?: string; value?: unknown }
    if (!p.table || !p.key) return { ok: false, error: 'table and key required' }
    if (!ctx.pluginStorage) return { ok: false, error: 'pluginStorage not available' }
    if (p.table !== 'settings' && p.table !== 'cache' && p.table !== 'state') {
      return { ok: false, error: 'table must be settings | cache | state' }
    }
    try {
      await ctx.pluginStorage.table(p.table).put(p.key, p.value)
      return { ok: true, data: { table: p.table, key: p.key, value: p.value } }
    } catch (err) {
      return { ok: false, error: (err as Error).message }
    }
  })

  // ── TODO: register your own tool endpoint(s) below ─────────────
  // ctx.on('{{pluginId}}/my-tool', (payload) => { ... })
}

;(plugin as PluginFn).inject = ['auditClient']
export default plugin