#!/usr/bin/env node
/**
 * dev.mjs — Start the workspace host + watch for plugin changes (HMR-style).
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * Usage: node scripts/dev.mjs
 *
 * This script:
 *   1. Resolves the local nx-pn binary from workspace root's node_modules
 *   2. Probes :4560; if down, spawns a detached host process with --data-dir
 *   3. Waits up to 60s for the host to become ready (Windows cold-start is slow)
 *   4. Uses the @flowot/nx-pn-hmr package to watch plugins/ and hot-rebuild
 *      on change (host's runId dedup hot-replaces the old run)
 */

import { spawn } from 'node:child_process'
import { readFile, readdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { Hmr, defaultConfig } from '@flowot/nx-pn-hmr'

// workspace root = two levels up from scripts/dev.mjs
const __root = dirname(dirname(fileURLToPath(import.meta.url)))
// Built nx-pn binary (workspace installs it via @flowot/nx-pn devDep)
const localBase = join(__root, 'node_modules', '@flowot', 'nx-pn', 'bin', 'nx-pn.mjs')

const PORT = process.env.NX_PN_PORT || 4560
const DATA_DIR = process.env.NX_PN_DATA_DIR || join(__root, '.data')
const HOST = `http://localhost:${PORT}`
const MAX_WAIT_MS = 60_000

async function probe(port) {
  try {
    const res = await fetch(`http://localhost:${port}/api/plugins`, { signal: AbortSignal.timeout(2000) })
    return res.ok
  } catch {
    return false
  }
}

async function waitForHost(maxMs) {
  const interval = 1000
  const deadline = Date.now() + maxMs
  while (Date.now() < deadline) {
    if (await probe(PORT)) return true
    await new Promise((r) => setTimeout(r, interval))
  }
  return false
}

async function spawnHost() {
  const child = spawn('node', [
    localBase,
    '--no-open',
    '--port', String(PORT),
    '--data-dir', DATA_DIR,
  ], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
    cwd: __root,
  })
  child.unref()
  console.log('[dev] spawned pid ' + child.pid + ' (detached)')

  const ready = await waitForHost(MAX_WAIT_MS)
  if (!ready) {
    console.error('[dev] FATAL: host did not become ready within ' + (MAX_WAIT_MS / 1000) + 's')
    console.error('[dev] try running manually: node "' + localBase + '" --no-open --port ' + PORT + ' --data-dir "' + DATA_DIR + '"')
    process.exit(1)
  }
  console.log('[dev] host ready at ' + HOST)
}

async function main() {
  console.log('[dev] probing ' + HOST + ' ...')
  if (await probe(PORT)) {
    console.log('[dev] host already running at ' + HOST)
  } else {
    console.log('[dev] no host detected — spawning local nx-pn ...')
    console.log('[dev] base: ' + localBase)
    console.log('[dev] data-dir: ' + DATA_DIR)
    await spawnHost()
  }
  console.log('[dev] done — connect to ' + HOST + ' in your browser')

  // Startup upload: build + hot-upload every plugin under plugins/ once the
  // host is up. Without this a fresh `npm run dev` only watches — the plugin
  // never reaches the host and its page 404s in the shell.
  const pluginsRoot = join(__root, 'plugins')
  const buildScript = join(__root, 'scripts', 'build.mjs')
  const pluginDirs = await readdir(pluginsRoot).catch(() => [])
  for (const dir of pluginDirs) {
    const pkgPath = join(pluginsRoot, dir, 'package.json')
    try {
      await readFile(pkgPath)
    } catch {
      continue // not a plugin package
    }
    console.log(`[dev] startup upload: ${dir}`)
    // inline build+upload (the standalone one-shot path; hmr is the long-running loop below)
    await new Promise((resolve) => {
      const child = spawn('node', [buildScript, dir], { cwd: __root, stdio: 'ignore' })
      child.on('close', () => resolve())
    }).then(async () => {
      try {
        const { readFile: rf } = await import('node:fs/promises')
        const zipPath = join(pluginsRoot, dir, 'dist', `${dir}.zip`)
        const zip = await rf(zipPath)
        const form = new FormData()
        form.append('zip', new Blob([zip]), `${dir}.zip`)
        await fetch(`${HOST}/api/plugins`, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) })
        console.log(`[dev] uploaded ${dir}`)
      } catch {}
    })
  }

  // Start HMR watcher via the @flowot/nx-pn-hmr package
  const hmr = new Hmr(defaultConfig({
    root: pluginsRoot,
    uploadUrl: HOST + '/api/plugins',
    pluginRoot: __root,
    build: (pluginId, pluginDir) => new Promise((resolve) => {
      const child = spawn('node', [buildScript, pluginId], { cwd: __root, stdio: ['ignore', 'pipe', 'pipe'] })
      let stdout = '', stderr = ''
      child.stdout?.on('data', (b) => { stdout += b.toString() })
      child.stderr?.on('data', (b) => { stderr += b.toString() })
      child.on('close', (code) => resolve({ code: code ?? 0, stdout, stderr }))
    }),
  }))
  hmr.start()
}

main().catch((err) => {
  console.error('[dev] FATAL:', err)
  process.exit(1)
})
