#!/usr/bin/env node
/**
 * dev.mjs — STANDALONE dev loop.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * Runs an isolated host owned by this terminal. The port must be free —
 * if another host is responding, dev exits loudly (run `shared-dev` instead
 * to join it).
 *
 * Usage:
 *   node scripts/dev.mjs            # own host on :4560 (or $NX_PN_PORT)
 *   NX_PN_PORT=4561 node scripts/dev.mjs
 *
 * Pipeline:
 *   1. probe :PORT — if a host is up, exit with guidance
 *   2. spawn a managed standalone host (parent tracks it for clean Ctrl+C
 *      shutdown), wait until :PORT/api/plugins responds
 *   3. startup-upload every plugin in plugins/ (build → dist/<id>.zip → POST)
 *   4. start the inline HMR watcher (node:fs.watch → rebuild → re-upload)
 *
 * Self-contained: no @flowot/nx-pn-hmr dep — the watcher is inlined.
 */

import { spawn } from 'node:child_process'
import { watch } from 'node:fs'
import { readFile, readdir, mkdir } from 'node:fs/promises'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const __root = dirname(dirname(fileURLToPath(import.meta.url)))
const localBase = join(__root, 'node_modules', '@flowot', 'nx-pn', 'bin', 'nx-pn.mjs')
const PORT = process.env.NX_PN_PORT || 4560
const DATA_DIR = process.env.NX_PN_DATA_DIR || join(__root, '.data')
const HOST = `http://localhost:${PORT}`
const MAX_WAIT_MS = 60_000

// ─ ─ ─ inline Hmr ─ ─ ─

const HMR_SKIP = /^(dist[/\\]|node_modules[/\\]|\.git[/\\]|\.data[/\\]|host\.js$|browser\.js$|manifest\.json$)/
const HMR_SOURCE = /\.(ts|tsx|json)$/

function pluginIdFromPath(root, filename) {
  const rel = relative(root, join(root, filename)).split(sep).join('/')
  if (!rel || rel.startsWith('..') || rel.startsWith('.')) return null
  return rel.split('/')[0] || null
}

async function uploadZip(uploadUrl, pluginId, zipBytes) {
  const form = new FormData()
  form.append('zip', new Blob([zipBytes]), `${pluginId}.zip`)
  const res = await fetch(uploadUrl, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) })
  const json = await res.json().catch(() => null)
  if (!res.ok || !json?.ok) {
    const e = json?.error
    throw new Error(`upload failed (HTTP ${res.status}${e ? `, ${e.code}: ${e.message}` : ''})`)
  }
  return json.data
}

class InlineHmr {
  constructor(opts) {
    this.root = opts.root
    this.uploadUrl = opts.uploadUrl
    this.buildScript = opts.buildScript
    this.cwd = opts.cwd
    this.debounceMs = opts.debounceMs ?? 500
    this._watcher = null
    this._pending = new Set()
    this._draining = new Set()
    this._timer = null
  }

  start() {
    if (this._watcher) return
    console.log(`[hmr] watching ${this.root} (Ctrl+C to exit)`)
    this._watcher = watch(this.root, { recursive: true }, (_ev, filename) => {
      if (!filename) return
      const rel = filename.split(sep).join('/')
      if (HMR_SKIP.test(rel) || !HMR_SOURCE.test(rel)) return
      const pluginId = pluginIdFromPath(this.root, filename)
      if (!pluginId) return
      console.log(`\n[hmr] change: ${rel}`)
      this._enqueue(pluginId)
    })
  }

  stop() {
    if (this._watcher) { this._watcher.close(); this._watcher = null }
    if (this._timer) { clearTimeout(this._timer); this._timer = null }
    this._pending.clear()
    this._draining.clear()
  }

  _enqueue(pluginId) {
    this._pending.add(pluginId)
    if (this._draining.has(pluginId)) return
    if (this._timer) clearTimeout(this._timer)
    this._timer = setTimeout(() => {
      this._timer = null
      for (const id of [...this._pending]) void this._drain(id)
    }, this.debounceMs)
  }

  async _drain(pluginId) {
    this._draining.add(pluginId)
    while (this._pending.has(pluginId)) {
      this._pending.delete(pluginId)
      const t0 = Date.now()
      console.log(`[hmr] rebuilding ${pluginId}...`)
      try {
        const pluginDir = join(this.root, pluginId)
        const { code, stdout, stderr } = await this._build(pluginId, pluginDir)
        if (code !== 0) throw new Error((stderr || stdout).trim() || `build exited ${code}`)
        const zipPath = join(this.cwd, 'dist', `${pluginId}.zip`)
        const zip = await readFile(zipPath)
        const data = await uploadZip(this.uploadUrl, pluginId, zip)
        const replaced = Array.isArray(data?.replaced) && data.replaced.length > 0
          ? ` (replaced ${data.replaced.join(', ')})`
          : ''
        console.log(`[hmr] ok ${pluginId} -> run=${data?.pluginRunId ?? '?'}${replaced} (${Date.now() - t0}ms)`)
      } catch (err) {
        console.log(`[hmr] failed ${pluginId}: ${err instanceof Error ? err.message : String(err)}`)
        console.log('      fix and save again to retry')
      }
    }
    this._draining.delete(pluginId)
  }

  _build(pluginId, pluginDir) {
    return new Promise((resolve) => {
      const child = spawn('node', [this.buildScript, pluginId], {
        cwd: this.cwd,
        stdio: ['ignore', 'pipe', 'pipe'],
      })
      let stdout = '', stderr = ''
      child.stdout?.on('data', (b) => { stdout += b.toString() })
      child.stderr?.on('data', (b) => { stderr += b.toString() })
      child.on('close', (code) => resolve({ code: code ?? 0, stdout, stderr }))
    })
  }
}

// ─ ─ ─ host lifecycle (probe / spawn / wait) ─ ─ ─

// Track the spawned host so Ctrl+C / SIGTERM can stop it cleanly. Without
// this the host is left running (and holding :PORT) after the dev script
// exits — detached+unref was the original cause.
let hostChild = null
let shuttingDown = false

function installShutdownHandlers() {
  const shutdown = (signal) => {
    if (shuttingDown) return
    shuttingDown = true
    console.log(`[dev] received ${signal}, stopping host...`)
    if (hostChild && hostChild.exitCode === null && hostChild.signalCode === null) {
      try { hostChild.kill('SIGINT') } catch {}
      const forceTimer = setTimeout(() => {
        if (hostChild && hostChild.exitCode === null && hostChild.signalCode === null) {
          console.error('[dev] host did not stop in 5s, force-killing')
          try { hostChild.kill('SIGKILL') } catch {}
        }
      }, 5000)
      forceTimer.unref()
      hostChild.once('exit', (code, sig) => {
        clearTimeout(forceTimer)
        process.exit(sig ? 1 : 0)
      })
    } else {
      process.exit(0)
    }
  }
  process.on('SIGINT', () => shutdown('SIGINT'))
  process.on('SIGTERM', () => shutdown('SIGTERM'))
}

async function probe(port) {
  try {
    const res = await fetch(`http://localhost:${port}/api/plugins`, { signal: AbortSignal.timeout(2000) })
    return res.ok
  } catch {
    return false
  }
}

async function waitForHost(maxMs) {
  const interval = 1000
  const deadline = Date.now() + maxMs
  while (Date.now() < deadline) {
    if (await probe(PORT)) return true
    await new Promise((r) => setTimeout(r, interval))
  }
  return false
}

async function spawnStandaloneHost() {
  await mkdir(DATA_DIR, { recursive: true })
  hostChild = spawn('node', [
    localBase,
    '--no-open',
    '--port', String(PORT),
    '--data-dir', DATA_DIR,
  ], {
    stdio: 'ignore',
    windowsHide: true,
    cwd: __root,
  })
  console.log(`[dev] spawned standalone pid ${hostChild.pid}`)

  const ready = await waitForHost(MAX_WAIT_MS)
  if (!ready) {
    console.error(`[dev] FATAL: standalone host did not become ready within ${MAX_WAIT_MS / 1000}s`)
    console.error(`[dev] try: node "${localBase}" --no-open --port ${PORT} --data-dir "${DATA_DIR}"`)
    process.exit(1)
  }
  console.log(`[dev] standalone host ready at ${HOST}`)
}

async function startupUpload(pluginsRoot, buildScript) {
  const pluginDirs = await readdir(pluginsRoot).catch(() => [])
  for (const dir of pluginDirs) {
    const pkgPath = join(pluginsRoot, dir, 'package.json')
    try {
      await readFile(pkgPath)
    } catch {
      continue
    }
    console.log(`[dev] startup upload: ${dir}`)
    await new Promise((resolve) => {
      const child = spawn('node', [buildScript, dir], { cwd: __root, stdio: 'ignore' })
      child.on('close', () => resolve())
    }).then(async () => {
      try {
        const zipPath = join(__root, 'dist', `${dir}.zip`)
        const zip = await readFile(zipPath)
        const form = new FormData()
        form.append('zip', new Blob([zip]), `${dir}.zip`)
        await fetch(`${HOST}/api/plugins`, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) })
        console.log(`[dev] uploaded ${dir}`)
      } catch {}
    })
  }
}

// ─ ─ ─ main: STANDALONE ─ ─ ─

async function main() {
  console.log('[dev] STANDALONE mode (own host)')
  console.log(`[dev] port=${PORT} data-dir=${DATA_DIR}`)
  installShutdownHandlers()

  if (await probe(PORT)) {
    console.error(`[dev] FATAL: :${PORT} already occupied by another host`)
    console.error('[dev] options:')
    console.error('[dev]   - run `npm run shared-dev` to join the existing host')
    console.error('[dev]   - or set NX_PN_PORT to a free port for a new standalone host')
    process.exit(1)
  }
  await spawnStandaloneHost()

  console.log(`[dev] done — connect to ${HOST} in your browser`)
  const pluginsRoot = join(__root, 'plugins')
  const buildScript = join(__root, 'scripts', 'build.mjs')
  await startupUpload(pluginsRoot, buildScript)
  const hmr = new InlineHmr({ root: pluginsRoot, uploadUrl: HOST + '/api/plugins', buildScript, cwd: __root })
  hmr.start()
}

main().catch((err) => {
  console.error('[dev] FATAL:', err)
  process.exit(1)
})