#!/usr/bin/env node
/**
 * shared-dev.mjs — SHARED dev loop.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * Joins (or creates) the shared host on :4560. Multiple shared-dev terminals
 * can run concurrently — the first one spawns the host, the rest upload to
 * the existing one. All watchers run locally and POST to the shared host.
 *
 * Usage:
 *   node scripts/shared-dev.mjs     # join :4560 (or spawn if none)
 *   NX_PN_PORT=4561 node scripts/shared-dev.mjs
 *
 * Pipeline:
 *   1. probe :PORT — if a host is up, join; otherwise spawn the shared host
 *   2. startup-upload every plugin in plugins/ to the shared host
 *   3. start the inline HMR watcher — changes POST to the shared host
 *
 * Self-contained: no @flowot/nx-pn-hmr dep — the watcher is inlined.
 * (This script duplicates the inline Hmr class from scripts/dev.mjs on
 * purpose — keeping dev/shared-dev fully standalone makes their different
 * host-mode logic obvious without chasing an import.)
 */

import { spawn } from 'node:child_process'
import { watch } from 'node:fs'
import { readFile, readdir, mkdir } from 'node:fs/promises'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const __root = dirname(dirname(fileURLToPath(import.meta.url)))
const localBase = join(__root, 'node_modules', '@flowot', 'nx-pn', 'bin', 'nx-pn.mjs')
const PORT = process.env.NX_PN_PORT || 4560
const DATA_DIR = process.env.NX_PN_DATA_DIR || join(__root, '.data')
const HOST = `http://localhost:${PORT}`
const MAX_WAIT_MS = 60_000

// ─ ─ ─ inline Hmr (duplicated from dev.mjs by design) ─ ─ ─

const HMR_SKIP = /^(dist[/\\]|node_modules[/\\]|\.git[/\\]|\.data[/\\]|host\.js$|browser\.js$|manifest\.json$)/
const HMR_SOURCE = /\.(ts|tsx|json)$/

function pluginIdFromPath(root, filename) {
  const rel = relative(root, join(root, filename)).split(sep).join('/')
  if (!rel || rel.startsWith('..') || rel.startsWith('.')) return null
  return rel.split('/')[0] || null
}

async function uploadZip(uploadUrl, pluginId, zipBytes) {
  const form = new FormData()
  form.append('zip', new Blob([zipBytes]), `${pluginId}.zip`)
  const res = await fetch(uploadUrl, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) })
  const json = await res.json().catch(() => null)
  if (!res.ok || !json?.ok) {
    const e = json?.error
    throw new Error(`upload failed (HTTP ${res.status}${e ? `, ${e.code}: ${e.message}` : ''})`)
  }
  return json.data
}

class InlineHmr {
  constructor(opts) {
    this.root = opts.root
    this.uploadUrl = opts.uploadUrl
    this.buildScript = opts.buildScript
    this.cwd = opts.cwd
    this.debounceMs = opts.debounceMs ?? 500
    this._watcher = null
    this._pending = new Set()
    this._draining = new Set()
    this._timer = null
  }

  start() {
    if (this._watcher) return
    console.log(`[hmr] watching ${this.root} (Ctrl+C to exit)`)
    this._watcher = watch(this.root, { recursive: true }, (_ev, filename) => {
      if (!filename) return
      const rel = filename.split(sep).join('/')
      if (HMR_SKIP.test(rel) || !HMR_SOURCE.test(rel)) return
      const pluginId = pluginIdFromPath(this.root, filename)
      if (!pluginId) return
      console.log(`\n[hmr] change: ${rel}`)
      this._enqueue(pluginId)
    })
  }

  stop() {
    if (this._watcher) { this._watcher.close(); this._watcher = null }
    if (this._timer) { clearTimeout(this._timer); this._timer = null }
    this._pending.clear()
    this._draining.clear()
  }

  _enqueue(pluginId) {
    this._pending.add(pluginId)
    if (this._draining.has(pluginId)) return
    if (this._timer) clearTimeout(this._timer)
    this._timer = setTimeout(() => {
      this._timer = null
      for (const id of [...this._pending]) void this._drain(id)
    }, this.debounceMs)
  }

  async _drain(pluginId) {
    this._draining.add(pluginId)
    while (this._pending.has(pluginId)) {
      this._pending.delete(pluginId)
      const t0 = Date.now()
      console.log(`[hmr] rebuilding ${pluginId}...`)
      try {
        const pluginDir = join(this.root, pluginId)
        const { code, stdout, stderr } = await this._build(pluginId, pluginDir)
        if (code !== 0) throw new Error((stderr || stdout).trim() || `build exited ${code}`)
        const zipPath = join(this.cwd, 'dist', `${pluginId}.zip`)
        const zip = await readFile(zipPath)
        const data = await uploadZip(this.uploadUrl, pluginId, zip)
        const replaced = Array.isArray(data?.replaced) && data.replaced.length > 0
          ? ` (replaced ${data.replaced.join(', ')})`
          : ''
        console.log(`[hmr] ok ${pluginId} -> run=${data?.pluginRunId ?? '?'}${replaced} (${Date.now() - t0}ms)`)
      } catch (err) {
        console.log(`[hmr] failed ${pluginId}: ${err instanceof Error ? err.message : String(err)}`)
        console.log('      fix and save again to retry')
      }
    }
    this._draining.delete(pluginId)
  }

  _build(pluginId, pluginDir) {
    return new Promise((resolve) => {
      const child = spawn('node', [this.buildScript, pluginId], {
        cwd: this.cwd,
        stdio: ['ignore', 'pipe', 'pipe'],
      })
      let stdout = '', stderr = ''
      child.stdout?.on('data', (b) => { stdout += b.toString() })
      child.stderr?.on('data', (b) => { stderr += b.toString() })
      child.on('close', (code) => resolve({ code: code ?? 0, stdout, stderr }))
    })
  }
}

// ─ ─ ─ host lifecycle (probe / spawn / wait) ─ ─ ─

async function probe(port) {
  try {
    const res = await fetch(`http://localhost:${port}/api/plugins`, { signal: AbortSignal.timeout(2000) })
    return res.ok
  } catch {
    return false
  }
}

async function waitForHost(maxMs) {
  const interval = 1000
  const deadline = Date.now() + maxMs
  while (Date.now() < deadline) {
    if (await probe(PORT)) return true
    await new Promise((r) => setTimeout(r, interval))
  }
  return false
}

async function spawnSharedHost() {
  await mkdir(DATA_DIR, { recursive: true })
  const child = spawn('node', [
    localBase,
    '--no-open',
    '--port', String(PORT),
    '--data-dir', DATA_DIR,
  ], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
    cwd: __root,
  })
  child.unref()
  console.log(`[dev] spawned shared host pid ${child.pid} (detached)`)

  const ready = await waitForHost(MAX_WAIT_MS)
  if (!ready) {
    console.error(`[dev] FATAL: shared host did not become ready within ${MAX_WAIT_MS / 1000}s`)
    console.error(`[dev] try: node "${localBase}" --no-open --port ${PORT} --data-dir "${DATA_DIR}"`)
    process.exit(1)
  }
  console.log(`[dev] shared host ready at ${HOST}`)
}

async function startupUpload(pluginsRoot, buildScript) {
  const pluginDirs = await readdir(pluginsRoot).catch(() => [])
  for (const dir of pluginDirs) {
    const pkgPath = join(pluginsRoot, dir, 'package.json')
    try {
      await readFile(pkgPath)
    } catch {
      continue
    }
    console.log(`[dev] startup upload: ${dir}`)
    await new Promise((resolve) => {
      const child = spawn('node', [buildScript, dir], { cwd: __root, stdio: 'ignore' })
      child.on('close', () => resolve())
    }).then(async () => {
      try {
        const zipPath = join(__root, 'dist', `${dir}.zip`)
        const zip = await readFile(zipPath)
        const form = new FormData()
        form.append('zip', new Blob([zip]), `${dir}.zip`)
        await fetch(`${HOST}/api/plugins`, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) })
        console.log(`[dev] uploaded ${dir}`)
      } catch {}
    })
  }
}

// ─ ─ ─ main: SHARED ─ ─ ─

async function main() {
  console.log('[dev] SHARED mode (join or spawn the shared host)')
  console.log(`[dev] port=${PORT} data-dir=${DATA_DIR}`)

  if (await probe(PORT)) {
    console.log(`[dev] shared host already running at ${HOST} — joining`)
  } else {
    console.log(`[dev] no host on :${PORT} — spawning shared host`)
    await spawnSharedHost()
  }

  console.log(`[dev] done — connect to ${HOST} in your browser`)
  const pluginsRoot = join(__root, 'plugins')
  const buildScript = join(__root, 'scripts', 'build.mjs')
  await startupUpload(pluginsRoot, buildScript)
  const hmr = new InlineHmr({ root: pluginsRoot, uploadUrl: HOST + '/api/plugins', buildScript, cwd: __root })
  hmr.start()
}

main().catch((err) => {
  console.error('[dev] FATAL:', err)
  process.exit(1)
})