/**
 * {{id}} — build the dual-half plugin.
 * Auto-generated by `npx @flowot/nx-pn init {{id}}`.
 *
 *   host.ts     → esbuild → host.js          (node, esm, external cordis)
 *   browser.tsx → esbuild → browser.js       (browser, esm, jsx automatic,
 *                                             react + cordis external)
 *   manifest.json (already at root, copied into the zip)
 *   → dist/{{id}}.zip  (STORED entries: manifest.json, host.js, browser.js)
 *
 * The compiled halves land at the package root on purpose: the host's
 * installer resolves `pkg.main` (`./host.js`) and imports from the root,
 * so a `npx @flowot/nx-pn add file:./{{id}}` install needs them here. The
 * zip just packages the same three root-level files for the upload path.
 */

import { build } from 'esbuild'
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const dist = join(root, 'dist')

await rm(dist, { recursive: true, force: true })
await mkdir(dist, { recursive: true })

await build({
  entryPoints: [join(root, 'host.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  external: ['cordis'],
  outfile: join(root, 'host.js'),
  logLevel: 'silent',
})

await build({
  entryPoints: [join(root, 'browser.tsx')],
  bundle: true,
  platform: 'browser',
  format: 'esm',
  target: 'es2022',
  jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client', 'react-router-dom', 'cordis'],
  outfile: join(root, 'browser.js'),
  logLevel: 'silent',
})

const compiledBrowser = await readFile(join(root, 'browser.js'), 'utf-8')
if (!/from\s*["']react["']/.test(compiledBrowser)) {
  throw new Error('{{id}}: compiled browser.js must keep React external')
}
if (!/from\s*["']react-router-dom["']/.test(compiledBrowser)) {
  throw new Error('{{id}}: compiled browser.js must keep react-router-dom external')
}

const entries = [
  ['manifest.json', await readFile(join(root, 'manifest.json'))],
  ['host.js', await readFile(join(root, 'host.js'))],
  ['browser.js', await readFile(join(root, 'browser.js'))],
]
const zip = makeZip(entries)
const zipPath = join(dist, '{{id}}.zip')
await writeFile(zipPath, zip)

console.log('{{id}}: built ' + zipPath + ' (' + zip.byteLength + ' bytes)')
console.log('  host.js, browser.js at package root (for npm install)')
for (const [name, data] of entries) {
  console.log('  zip[' + name + ']: ' + data.length + ' bytes')
}

function crc32(buf) {
  let c = 0xffffffff
  for (let i = 0; i < buf.byteLength; i++) {
    c ^= buf[i]
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1))
  }
  return (c ^ 0xffffffff) >>> 0
}

function makeZip(parts) {
  const local = []
  const central = []
  let offset = 0
  for (const [name, data] of parts) {
    const nameBuf = Buffer.from(name, 'utf-8')
    const lfh = Buffer.alloc(30)
    lfh.writeUInt32LE(0x04034b50, 0)
    lfh.writeUInt16LE(20, 4)
    lfh.writeUInt16LE(0, 6)
    lfh.writeUInt16LE(0, 8)
    lfh.writeUInt32LE(crc32(data), 14)
    lfh.writeUInt32LE(data.byteLength, 18)
    lfh.writeUInt32LE(data.byteLength, 22)
    lfh.writeUInt16LE(nameBuf.byteLength, 26)
    local.push(lfh, nameBuf, data)
    const cdh = Buffer.alloc(46)
    cdh.writeUInt32LE(0x02014b50, 0)
    cdh.writeUInt16LE(20, 4)
    cdh.writeUInt16LE(20, 6)
    cdh.writeUInt32LE(crc32(data), 16)
    cdh.writeUInt32LE(data.byteLength, 20)
    cdh.writeUInt32LE(data.byteLength, 24)
    cdh.writeUInt16LE(nameBuf.byteLength, 28)
    cdh.writeUInt32LE(offset, 42)
    central.push(cdh, nameBuf)
    offset += 30 + nameBuf.byteLength + data.byteLength
  }
  const localBuf = Buffer.concat(local)
  const cdBuf = Buffer.concat(central)
  const eocd = Buffer.alloc(22)
  eocd.writeUInt32LE(0x06054b50, 0)
  eocd.writeUInt16LE(parts.length, 8)
  eocd.writeUInt16LE(parts.length, 10)
  eocd.writeUInt32LE(cdBuf.byteLength, 12)
  eocd.writeUInt32LE(localBuf.byteLength, 16)
  return Buffer.concat([localBuf, cdBuf, eocd])
}
