/**
 * my-plugin — browser half of My Plugin.
 * Auto-generated by `npx @flowot/nx-pn init <name>`.
 *
 * ── 页面级别 / 全屏级别 ─────────────────────────────────────────────
 * ctx.pages.register 的 `layout` 字段控制页面如何挂进 WebShell：
 *   - layout: 'shell'      （默认）页面嵌在壳里，自动出现在侧栏，
 *                          自带审计记录/API 重放等平台导航。
 *   - layout: 'fullscreen' 全屏页面，侧栏隐藏，需要自己渲染顶栏/导航。
 * 改下面 register 里的 layout 值即可切换，其余代码不用动。
 * ────────────────────────────────────────────────────────────────────
 */

import { useState } from 'react'

interface BrowserCtx {
  logger: { info(m: string): void }
  pages: {
    register(entry: {
      pluginId: string
      path: string
      title: string
      order?: number
      /** 'shell'（进侧栏，默认）| 'fullscreen'（全屏，隐藏侧栏） */
      layout?: 'shell' | 'fullscreen'
      Component?: unknown
    }): unknown
  }
}

const browserHalf = function browserHalf(ctx: BrowserCtx, config?: { name?: string }): void {
  const id = config?.name ?? 'my-plugin'
  ctx.logger.info(`[${id}] browser half active`)

  // 最简可用页面：改成你自己的 UI 即可
  const PageComponent = () => {
    const [count, setCount] = useState(0)
    return (
      <div className="page">
        <h1>My Plugin</h1>
        <div className="muted">Plugin <code>{id}</code> browser half.</div>
        <section className="card">
          <h2>HMR Hot Update Works</h2>
          <p>useState counter: <strong>{count}</strong></p>
          <div className="form-actions">
            <button onClick={() => setCount((c) => c + 1)}>Increment</button>
          </div>
        </section>
      </div>
    )
  }

  ctx.pages.register({
    pluginId: id,
    path: '/' + id,
    title: 'My Plugin',
    order: 200,
    // 二选一：'shell' 进侧栏（默认）| 'fullscreen' 全屏（侧栏隐藏，自带导航）
    layout: 'shell',
    Component: PageComponent,
  })
}

;(browserHalf as typeof browserHalf & { inject?: string[] }).inject = ['pages']
export default browserHalf
