/**
 * {{id}} — browser half of {{title}}.
 * Auto-generated by `npx @flowot/nx-pn init {{id}}`.
 */

import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

interface BrowserCtx {
  logger: { info(m: string): void }
  pages: {
    register(entry: { pluginId: string; path: string; title: string; order?: number; Component?: unknown }): unknown
  }
}

const browserHalf = function browserHalf(ctx: BrowserCtx, config?: { name?: string }): void {
  const id = config?.name ?? '{{id}}'
  ctx.logger.info(`[${id}] browser half active — registering {{path}}`)

  const {{pageComponentName}} = () => {
    const [count, setCount] = useState(0)
    const navigate = useNavigate()
    return (
      <div className="page">
        <h1>{{title}}</h1>
        <div className="muted">本页由 <code>{id}</code> 浏览器半动态注册。</div>
        <section className="card">
          <h2>共享 React 校验</h2>
          <p>本页使用宿主 web 应用的同一份 React（import map 共享）。</p>
          <ul>
            <li>useState hook：<strong>{count}</strong> 次。</li>
            <li>react-router-dom：本页是 <code>{{path}}</code>。</li>
          </ul>
          <div className="form-actions">
            <button onClick={() => setCount((c) => c + 1)}>点我</button>
            <button onClick={() => navigate('/audit')}>跳到审计记录 →</button>
          </div>
        </section>
        <section className="card">
          <h2>下一步</h2>
          <p>编辑 <code>browser.tsx</code> 加你的 UI，<code>host.ts</code> 加服务端逻辑，再 <code>npm run build</code>。</p>
        </section>
      </div>
    )
  }

  ctx.pages.register({
    pluginId: id,
    path: '{{path}}',
    title: '{{title}}',
    order: 200,
    Component: {{pageComponentName}},
  })
}

;(browserHalf as typeof browserHalf & { inject?: string[] }).inject = ['pages']
export default browserHalf
