/**
 * {{id}} — host half of {{title}}.
 * Auto-generated by `npx @flowot/nx-pn init {{id}}`.
 *
 * Lifecycle:
 *   - registered by the host plugin loader (esbuild → import → ctx.plugin)
 *   - any ctx.auditClient.get/post/... is attributed to "{{id}}"
 *
 * What this scaffold does:
 *   1. Fires one hello-call at activation so a fresh install already
 *      shows a record on /audit attributed to {{id}}.
 *   2. Registers no tool endpoint — extend below.
 */

interface HostCtx {
  logger: { info(m: string): void; warn(m: string): void; error(m: string): void }
  on(event: string, handler: (payload?: unknown) => unknown): unknown
  auditClient: {
    get(url: string, config?: { headers?: Record<string, string>; timeoutMs?: number }): Promise<{ status: number; statusText: string; bodyText: string }>
  }
}

type PluginFn = ((ctx: HostCtx, config?: { name?: string }) => void) & { inject?: string[] }

const DEFAULT_URL = 'https://httpbin.org/get'

const plugin = function plugin(ctx: HostCtx, config?: { name?: string }): void {
  const id = config?.name ?? '{{id}}'
  ctx.logger.info(`[${id}] host half active`)

  // Hello at activation — fire-and-forget.
  void ctx.auditClient.get(DEFAULT_URL, { headers: { 'user-agent': '{{user-agent}}' } }).catch(() => {
    /* recorded by the audit middleware */
  })

  // ── TODO: register your tool endpoint(s) here ─────────────────────
  // ctx.on('{{id}}/my-tool', (payload) => {
  //   const url = ...
  //   return ctx.auditClient.get(url)
  // })
}

;(plugin as PluginFn).inject = ['auditClient']
export default plugin
